const { Router } = require("express")
const homeRouter = Router()
const userController = require("../controllers/userController")
const bestsellerController = require("../controllers/bestsellerController")
const commentController = require("../controllers/commentController")
const showProductController = require("../controllers/showProductController")
const categoryController = require("../controllers/categoryController")
const localstorageproductController = require("../controllers/localstorageproductController")
const productContoller = require("../controllers/productContoller")
const orderController = require("../controllers/orderController")
const searchController = require("../controllers/searchController")
const filterParamsController = require("../controllers/filterParamsController")

homeRouter.post("/user", userController.checkUserController)
homeRouter.post("/verific", userController.verification)
homeRouter.get("/bestsellers", bestsellerController.getBestseller)
homeRouter.get("/bestsellercount", bestsellerController.bestsellerCount)
homeRouter.post("/addcomment", commentController.addComment)
homeRouter.use("/show", showProductController.ShowProduct)
homeRouter.get("/similarproduct", showProductController.SimilarProduct)
homeRouter.get("/similarproductcount", showProductController.SimilarProductCount)
homeRouter.post("/catalog", categoryController.getProductOnCategory)
homeRouter.post("/catalogcount", categoryController.productCategoryCount)
homeRouter.post("/localstorageproduct", localstorageproductController.requestArrayId)
homeRouter.get("/localstorage-product-getone/:id", localstorageproductController.requestOneId)
homeRouter.delete("/productdelete/:id", productContoller.praductDelete)
homeRouter.get("/receivecomment", commentController.receiveComment)
homeRouter.get("/receivecommentcount", commentController.receiveCommentCount)
homeRouter.delete("/deletcomment/:id", commentController.deleteComment)
homeRouter.put("/updateproductcomments/:id", productContoller.updatePraductComments)
homeRouter.post("/order", orderController.createOrder)
homeRouter.get("/searchcount", searchController.searchProductCount)
homeRouter.get("/searchquery", searchController.searchProduct)
homeRouter.get("/filter", filterParamsController.filterParams)



module.exports = homeRouter